import os
import django
from django.db import connection

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings')
django.setup()

with connection.cursor() as cursor:
    cursor.execute('ALTER TABLE backend_gamesession ADD COLUMN hints_given jsonb DEFAULT ''[]''::jsonb NOT NULL;')
    cursor.execute('''
    CREATE TABLE backend_userhintquota (
        id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        date date NOT NULL,
        count integer NOT NULL,
        user_id integer NOT NULL UNIQUE REFERENCES auth_user (id) DEFERRABLE INITIALLY DEFERRED
    );
    ''')

